spring:
  application:
      name: cloud-discovery-client-consul
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        enabled: true
        prefer-ip-address: true
server:
  port: 9090


