server:
  port: 8765
spring:
  application:
    name: cloud-feign-hello
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        enabled: true
        prefer-ip-address: true
      enabled: true
