server:
  port: 8764

spring:
  application:
    name: battcn-cloud-ribbon
  cloud:
    consul:
      host: localhost
      port: 8500
      enabled: true
      discovery:
        enabled: true
        prefer-ip-address: true